Implement command to delete tag
AY2425S1-CS2103T-F14a-4/tp pull request #105
Opened 2024-10-20 14:07 UTC by CYX22222003

2024-10-20 15:11 UTC, CYX22222003 commented on src/main/java/seedu/address/model/person/UniquePersonList.java
> +    /**
I reutilize the setPerson logic. Directly delete from a person's tag list will cause invocation errors while reloading UI

2024-10-22 08:28 UTC, KrashKart requested changes
LGTM! Maybe a few minor changes before merging

2024-10-22 11:12 UTC, CYX22222003 commented on src/main/java/seedu/address/model/person/Person.java
> +
Because the `this.getTags().remove(t)` cause `invocationTargetException` being thrown when loading the UI. So I reuse the logic of `setPerson` here

2024-10-22 16:02 UTC, KrashKart approved these changes
LGTM! Paisei for the comments

2024-10-22 16:11 UTC, merged