Branch UI update
AY2425S1-CS2103T-F14a-4/tp pull request #107
Opened 2024-10-20 18:21 UTC by yooplo

This should 
- Improve visibility of menu options
- Improve display for list of tags
- Delete unnecessary css themes
- Add mouse hover animation on the personsList and tagsList

Current Bug:
The tag list only updates when you restart the app.
It does not update in real time.

2024-10-20 18:33 UTC, yooplo commented
Closes #102

2024-10-21 01:27 UTC, KrashKart requested changes
Mostly LGTM! Maybe 1-2 very small changes

2024-10-21 01:27 UTC, KrashKart commented on src/main/java/seedu/address/ui/TagCard.java
> +}
Should be sufficient to contain each individual card

2024-10-21 01:27 UTC, KrashKart commented on src/main/java/seedu/address/model/ModelManager.java
> +        return this.currentlyDefinedTags;
Think since you need to display the tags sorted, can sort the tags here before passing it to the TagListPanel

2024-10-21 01:27 UTC, KrashKart commented on src/main/java/seedu/address/ui/TagListPanel.java
> +}
Should be sufficient to display the tags list!

2024-10-21 04:30 UTC, yooplo commented
![image](https://github.com/user-attachments/assets/f9385998-c20d-4252-b05f-6b4ba66286c4)

This is what the new GUI would look like

2024-10-21 05:15 UTC, KrashKart approved these changes
LGTM! Let's merge

2024-10-21 05:35 UTC, merged