Update manual testing guide for addtag command
AY2425S1-CS2103T-F14a-4/tp pull request #277
Opened 2024-11-07 15:44 UTC by blackpanther9229

2024-11-07 15:47 UTC, CYX22222003 submitted a review, later dismissed

2024-11-07 15:47 UTC, CYX22222003 commented on docs/DeveloperGuide.md
> +1. Deleting a tag while all tags are being shown
should it be adding

2024-11-10 03:11 UTC, KrashKart requested changes
LGTM! Just some minor changes

2024-11-10 03:11 UTC, KrashKart commented on docs/DeveloperGuide.md
> +         Expected: No new tag added. Error details shown in the status message. All status bar remain the same.
There is no status bar.

2024-11-10 09:01 UTC, KrashKart approved these changes
LGTM!

2024-11-10 09:02 UTC, merged